import sqlite3
connection = sqlite3.connect("itstep_DB.sl3", 5)
cur = connection.cursor()
cur.execute("INSERT INTO first_table (name) VALUES ('Anna');")
cur.execute("INSERT INTO first_table (name) VALUES ('Kate');")
cur.execute("INSERT INTO first_table (name) VALUES ('John');")
connection.commit()
cur.execute("UPDATE first_table SET name='Kate' WHERE rowid=3;")
connection.commit()
res = cur.fetchall()
print(res)
connection.close()